[2024-04-24T09:37:55.565+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: use_case_dag.task_1 manual__2024-04-24T09:37:53.666524+00:00 [queued]>
[2024-04-24T09:37:55.576+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: use_case_dag.task_1 manual__2024-04-24T09:37:53.666524+00:00 [queued]>
[2024-04-24T09:37:55.577+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-24T09:37:55.593+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): task_1> on 2024-04-24 09:37:53.666524+00:00
[2024-04-24T09:37:55.603+0000] {standard_task_runner.py:60} INFO - Started process 8548 to run task
[2024-04-24T09:37:55.608+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'use_case_dag', 'task_1', 'manual__2024-04-24T09:37:53.666524+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/use_case_dag.py', '--cfg-path', '/tmp/tmp5ynfbgux']
[2024-04-24T09:37:55.613+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask task_1
[2024-04-24T09:37:55.679+0000] {task_command.py:423} INFO - Running <TaskInstance: use_case_dag.task_1 manual__2024-04-24T09:37:53.666524+00:00 [running]> on host 426889f50441
[2024-04-24T09:37:55.792+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='matteo' AIRFLOW_CTX_DAG_ID='use_case_dag' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T09:37:53.666524+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T09:37:53.666524+00:00'
[2024-04-24T09:38:11.422+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-24T09:38:11.440+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=use_case_dag, task_id=task_1, execution_date=20240424T093753, start_date=20240424T093755, end_date=20240424T093811
[2024-04-24T09:38:11.483+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-24T09:38:11.508+0000] {dagrun.py:885} ERROR - Failed to get task for ti <TaskInstance: use_case_dag.task_3 manual__2024-04-24T09:37:53.666524+00:00 [None]>. Marking it as removed.
[2024-04-24T09:38:11.519+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
